// src/modules/instituteadmin/mock-drive/batch/batch.types.ts

import { MockDriveBatchStatus, MockDriveRegistrationStatus, MockDriveAttemptStatus } from '@prisma/client';

// ============================================
// DTOs
// ============================================

export interface CreateBatchDTO {
  name: string;
  scheduledStartTime: Date;
  scheduledEndTime: Date;
  maxCapacity?: number | null;
  notes?: string | null;
}

export interface UpdateBatchDTO {
  name?: string;
  scheduledStartTime?: Date;
  scheduledEndTime?: Date;
  maxCapacity?: number | null;
  notes?: string | null;
  status?: MockDriveBatchStatus;
}

export interface AutoCreateBatchesDTO {
  batchSize: number;
  startTime: Date;
  intervalMinutes: number;
  prefix?: string;
}

export interface AssignStudentsDTO {
  registrationIds: string[];
}

// ============================================
// Query Types
// ============================================

export interface ListBatchesQuery {
  page?: number;
  limit?: number;
  status?: MockDriveBatchStatus;
  sortBy?: 'scheduledStartTime' | 'batchNumber' | 'createdAt';
  sortOrder?: 'asc' | 'desc';
}

// ============================================
// Response Types
// ============================================

export interface BatchStats {
  totalAssigned: number;
  totalStarted: number;
  totalCompleted: number;
  totalInProgress: number;
  averageScore: number | null;
}

export interface BatchDetails {
  id: string;
  mockDriveId: string;
  name: string;
  batchNumber: number;
  scheduledStartTime: Date;
  scheduledEndTime: Date;
  status: MockDriveBatchStatus;
  maxCapacity: number | null;
  isAutoGenerated: boolean;
  notes: string | null;
  actualStartTime: Date | null;
  actualEndTime: Date | null;
  createdAt: Date;
  updatedAt: Date;
  stats: BatchStats;
}

export interface BatchListItem {
  id: string;
  name: string;
  batchNumber: number;
  scheduledStartTime: Date;
  scheduledEndTime: Date;
  status: MockDriveBatchStatus;
  maxCapacity: number | null;
  assignedCount: number;
  completedCount: number;
  inProgressCount: number;
}

export interface PaginatedBatches {
  data: BatchListItem[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    hasNext: boolean;
    hasPrevious: boolean;
  };
}

export interface BatchStudent {
  registrationId: string;
  userId: string;
  studentName: string;
  studentId: string;
  departmentId: string;
  courseYear: string;
  registrationStatus: MockDriveRegistrationStatus;
  attemptStatus: MockDriveAttemptStatus | null;
  attemptScore: number | null;
}

export interface AssignResult {
  assigned: number;
  failed: string[];
}

export interface UnassignResult {
  unassigned: number;
}

// ============================================
// Error Classes
// ============================================

export class BatchError extends Error {
  constructor(
    public code: string,
    message: string,
    public statusCode: number = 400
  ) {
    super(message);
    this.name = 'BatchError';
  }
}

export class BatchNotFoundError extends BatchError {
  constructor(batchId: string) {
    super('BATCH_NOT_FOUND', `Batch not found: ${batchId}`, 404);
  }
}

export class BatchCapacityExceededError extends BatchError {
  constructor(batchId: string, capacity: number) {
    super('BATCH_CAPACITY_EXCEEDED', `Batch capacity exceeded. Maximum: ${capacity}`, 400);
  }
}

export class BatchStatusError extends BatchError {
  constructor(status: MockDriveBatchStatus, action: string) {
    super('BATCH_INVALID_STATUS', `Cannot ${action} batch with status: ${status}`, 400);
  }
}

export class BatchScheduleConflictError extends BatchError {
  constructor(message: string) {
    super('BATCH_SCHEDULE_CONFLICT', message, 400);
  }
}

export class BatchHasAttemptsError extends BatchError {
  constructor() {
    super('BATCH_HAS_ATTEMPTS', 'Cannot modify batch with existing attempts', 400);
  }
}