// src/modules/instituteadmin/mock-drive/batch/batch.service.ts

import {
  Prisma,
  MockDriveBatchStatus,
  MockDriveRegistrationStatus,
  MockDriveStatus,
  MockDriveAttemptStatus,
} from '@prisma/client';
import { prisma } from '../../../../lib/db';
import { logger } from '../../../../utils/logger';
import {
  CreateBatchDTO,
  UpdateBatchDTO,
  AutoCreateBatchesDTO,
  AssignStudentsDTO,
  ListBatchesQuery,
  BatchDetails,
  BatchListItem,
  BatchStats,
  PaginatedBatches,
  BatchStudent,
  AssignResult,
  UnassignResult,
  BatchNotFoundError,
  BatchCapacityExceededError,
  BatchStatusError,
  BatchScheduleConflictError,
  BatchError,
} from './batch.types';

// ============================================
// Constants
// ============================================

const DEFAULT_PAGE = 1;
const DEFAULT_LIMIT = 20;

// ============================================
// Types
// ============================================

interface MockDriveInfo {
  id: string;
  status: MockDriveStatus;
  instituteId: string;
  driveStartDate: Date | null;
  driveEndDate: Date | null;
  totalModuleTime: number;
}

// ============================================
// Custom Errors (inline to avoid circular imports)
// ============================================

class MockDriveNotFoundError extends Error {
  code = 'MOCK_DRIVE_NOT_FOUND';
  statusCode = 404;
  constructor(id: string) {
    super(`Mock drive not found: ${id}`);
  }
}

class MockDriveAccessDeniedError extends Error {
  code = 'ACCESS_DENIED';
  statusCode = 403;
  constructor() {
    super('Access denied to this mock drive');
  }
}

class MockDriveInvalidStatusError extends Error {
  code = 'INVALID_STATUS';
  statusCode = 400;
  constructor(status: MockDriveStatus, action: string) {
    super(`Cannot ${action} when mock drive status is ${status}`);
  }
}

// ============================================
// Service Class
// ============================================

export class BatchService {
  // ==========================================
  // Create Batch
  // ==========================================

  async createBatch(
    mockDriveId: string,
    instituteId: string,
    data: CreateBatchDTO
  ): Promise<BatchDetails> {
    const mockDrive = await this.verifyAccess(mockDriveId, instituteId);
    this.validateStatusForBatchOps(mockDrive.status);
    this.validateTimeWithinDrive(mockDrive, data.scheduledStartTime, data.scheduledEndTime);
    await this.checkScheduleConflict(mockDriveId, data.scheduledStartTime, data.scheduledEndTime);

    const batchNumber = await this.getNextBatchNumber(mockDriveId);

    const batch = await prisma.mockDriveBatch.create({
      data: {
        mockDriveId,
        name: data.name,
        batchNumber,
        scheduledStartTime: data.scheduledStartTime,
        scheduledEndTime: data.scheduledEndTime,
        maxCapacity: data.maxCapacity ?? null,
        notes: data.notes ?? null,
        isAutoGenerated: false,
        status: MockDriveBatchStatus.CREATED,
      },
    });

    logger.info('Batch created', { mockDriveId, batchId: batch.id, batchNumber });
    return this.getBatchDetails(batch.id);
  }

  // ==========================================
  // Get Batch by ID
  // ==========================================

  async getBatchById(
    mockDriveId: string,
    batchId: string,
    instituteId: string
  ): Promise<BatchDetails> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    return this.getBatchDetails(batchId);
  }

  // ==========================================
  // List Batches
  // ==========================================

  async listBatches(
    mockDriveId: string,
    instituteId: string,
    query: ListBatchesQuery
  ): Promise<PaginatedBatches> {
    await this.verifyAccess(mockDriveId, instituteId);

    const {
      page = DEFAULT_PAGE,
      limit = DEFAULT_LIMIT,
      status,
      sortBy = 'scheduledStartTime',
      sortOrder = 'asc',
    } = query;

    const skip = (page - 1) * limit;
    const where: Prisma.MockDriveBatchWhereInput = {
      mockDriveId,
      ...(status && { status }),
    };

    const [batches, total] = await Promise.all([
      prisma.mockDriveBatch.findMany({
        where,
        skip,
        take: limit,
        orderBy: { [sortBy]: sortOrder },
        include: {
          _count: { select: { registrations: true } },
        },
      }),
      prisma.mockDriveBatch.count({ where }),
    ]);

    // Get attempt counts per batch
    const batchIds = batches.map((b) => b.id);
    const attemptCounts = await this.getAttemptCountsByBatch(batchIds);

    const totalPages = Math.ceil(total / limit);

    return {
      data: batches.map((b): BatchListItem => ({
        id: b.id,
        name: b.name,
        batchNumber: b.batchNumber,
        scheduledStartTime: b.scheduledStartTime,
        scheduledEndTime: b.scheduledEndTime,
        status: b.status,
        maxCapacity: b.maxCapacity,
        assignedCount: b._count.registrations,
        completedCount: attemptCounts.get(b.id)?.completed ?? 0,
        inProgressCount: attemptCounts.get(b.id)?.inProgress ?? 0,
      })),
      pagination: {
        page,
        limit,
        total,
        totalPages,
        hasNext: page < totalPages,
        hasPrevious: page > 1,
      },
    };
  }

  // ==========================================
  // Update Batch
  // ==========================================

  async updateBatch(
    mockDriveId: string,
    batchId: string,
    instituteId: string,
    data: UpdateBatchDTO
  ): Promise<BatchDetails> {
    const mockDrive = await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    // Validate status transition
    if (data.status) {
      this.validateStatusTransition(batch.status, data.status);
    }

    // Restrict updates for active batches
    if (batch.status === MockDriveBatchStatus.IN_PROGRESS || 
        batch.status === MockDriveBatchStatus.COMPLETED) {
      this.validateActiveUpdateFields(data, batch.status);
    }

    // Validate time changes
    if (data.scheduledStartTime || data.scheduledEndTime) {
      const newStart = data.scheduledStartTime ?? batch.scheduledStartTime;
      const newEnd = data.scheduledEndTime ?? batch.scheduledEndTime;
      this.validateTimeWithinDrive(mockDrive, newStart, newEnd);
      await this.checkScheduleConflict(mockDriveId, newStart, newEnd, batchId);
    }

    const updateData = this.buildUpdateData(data);

    await prisma.mockDriveBatch.update({
      where: { id: batchId },
      data: updateData,
    });

    logger.info('Batch updated', { batchId });
    return this.getBatchDetails(batchId);
  }

  // ==========================================
  // Delete Batch
  // ==========================================

  async deleteBatch(
    mockDriveId: string,
    batchId: string,
    instituteId: string
  ): Promise<void> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
      include: { _count: { select: { attempts: true } } },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    if (batch._count.attempts > 0) {
      throw new BatchError('BATCH_HAS_ATTEMPTS', 'Cannot delete batch with attempts', 400);
    }

    if (batch.status === MockDriveBatchStatus.IN_PROGRESS || 
        batch.status === MockDriveBatchStatus.COMPLETED) {
      throw new BatchStatusError(batch.status, 'delete');
    }

    // Unassign students first
    await prisma.mockDriveRegistration.updateMany({
      where: { batchId },
      data: { batchId: null },
    });

    await prisma.mockDriveBatch.delete({ where: { id: batchId } });

    logger.info('Batch deleted', { batchId });
  }

  // ==========================================
  // Auto Create Batches
  // ==========================================

  async autoCreateBatches(
    mockDriveId: string,
    instituteId: string,
    data: AutoCreateBatchesDTO
  ): Promise<BatchDetails[]> {
    const mockDrive = await this.verifyAccess(mockDriveId, instituteId);
    this.validateStatusForBatchOps(mockDrive.status);

    const unassigned = await prisma.mockDriveRegistration.findMany({
      where: {
        mockDriveId,
        status: MockDriveRegistrationStatus.APPROVED,
        batchId: null,
      },
      orderBy: { registeredAt: 'asc' },
    });

    if (unassigned.length === 0) {
      return [];
    }

    let batchNumber = await this.getNextBatchNumber(mockDriveId);
    const durationMinutes = mockDrive.totalModuleTime || 60;
    let currentStart = new Date(data.startTime);
    const createdBatches: BatchDetails[] = [];

    for (let i = 0; i < unassigned.length; i += data.batchSize) {
      const batchRegs = unassigned.slice(i, i + data.batchSize);
      const endTime = new Date(currentStart.getTime() + durationMinutes * 60000);

      // Stop if outside drive window
      if (mockDrive.driveEndDate && endTime > mockDrive.driveEndDate) {
        break;
      }

      const batch = await prisma.mockDriveBatch.create({
        data: {
          mockDriveId,
          name: `${data.prefix || 'Batch'} ${batchNumber}`,
          batchNumber,
          scheduledStartTime: currentStart,
          scheduledEndTime: endTime,
          maxCapacity: data.batchSize,
          isAutoGenerated: true,
          status: MockDriveBatchStatus.CREATED,
        },
      });

      await prisma.mockDriveRegistration.updateMany({
        where: { id: { in: batchRegs.map((r) => r.id) } },
        data: { batchId: batch.id },
      });

      createdBatches.push(await this.getBatchDetails(batch.id));

      batchNumber++;
      currentStart = new Date(currentStart.getTime() + data.intervalMinutes * 60000);
    }

    logger.info('Auto-created batches', { mockDriveId, count: createdBatches.length });
    return createdBatches;
  }

  // ==========================================
  // Assign Students
  // ==========================================

  async assignStudents(
    mockDriveId: string,
    batchId: string,
    instituteId: string,
    data: AssignStudentsDTO
  ): Promise<AssignResult> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
      include: { _count: { select: { registrations: true } } },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    if (batch.status === MockDriveBatchStatus.COMPLETED || 
        batch.status === MockDriveBatchStatus.CANCELLED) {
      throw new BatchStatusError(batch.status, 'assign students');
    }

    // Check capacity
    if (batch.maxCapacity) {
      const newTotal = batch._count.registrations + data.registrationIds.length;
      if (newTotal > batch.maxCapacity) {
        throw new BatchCapacityExceededError(batchId, batch.maxCapacity);
      }
    }

    const registrations = await prisma.mockDriveRegistration.findMany({
      where: { id: { in: data.registrationIds }, mockDriveId },
      select: { id: true, status: true, batchId: true },
    });

    const validIds: string[] = [];
    const failedIds: string[] = [];

    for (const regId of data.registrationIds) {
      const reg = registrations.find((r) => r.id === regId);
      
      if (!reg || reg.status !== MockDriveRegistrationStatus.APPROVED || 
          (reg.batchId && reg.batchId !== batchId)) {
        failedIds.push(regId);
      } else {
        validIds.push(regId);
      }
    }

    if (validIds.length > 0) {
      await prisma.mockDriveRegistration.updateMany({
        where: { id: { in: validIds } },
        data: { batchId },
      });
    }

    logger.info('Students assigned', { batchId, assigned: validIds.length, failed: failedIds.length });
    return { assigned: validIds.length, failed: failedIds };
  }

  // ==========================================
  // Unassign Students
  // ==========================================

  async unassignStudents(
    mockDriveId: string,
    batchId: string,
    instituteId: string,
    registrationIds: string[]
  ): Promise<UnassignResult> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    if (batch.status === MockDriveBatchStatus.IN_PROGRESS || 
        batch.status === MockDriveBatchStatus.COMPLETED) {
      throw new BatchStatusError(batch.status, 'unassign students');
    }

    // Check for attempts
    const hasAttempts = await prisma.mockDriveAttempt.findFirst({
      where: {
        batchId,
        userId: {
          in: await prisma.mockDriveRegistration.findMany({
            where: { id: { in: registrationIds } },
            select: { userId: true },
          }).then((regs) => regs.map((r) => r.userId)),
        },
      },
    });

    if (hasAttempts) {
      throw new BatchError('CANNOT_UNASSIGN', 'Cannot unassign students with attempts', 400);
    }

    const result = await prisma.mockDriveRegistration.updateMany({
      where: { id: { in: registrationIds }, batchId },
      data: { batchId: null },
    });

    logger.info('Students unassigned', { batchId, count: result.count });
    return { unassigned: result.count };
  }

  // ==========================================
  // Get Batch Students
  // ==========================================

  async getBatchStudents(
    mockDriveId: string,
    batchId: string,
    instituteId: string
  ): Promise<BatchStudent[]> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    const registrations = await prisma.mockDriveRegistration.findMany({
      where: { batchId },
      include: { user: { include: { profile: true } } },
    });

    const userIds = registrations.map((r) => r.userId);
    const attempts = await prisma.mockDriveAttempt.findMany({
      where: { batchId, userId: { in: userIds } },
      select: { userId: true, status: true, totalScore: true },
    });

    const attemptMap = new Map(attempts.map((a) => [a.userId, a]));

    return registrations.map((r): BatchStudent => {
      const attempt = attemptMap.get(r.userId);
      return {
        registrationId: r.id,
        userId: r.userId,
        studentName: r.user.profile?.fullName ?? r.user.name ?? 'Unknown',
        studentId: r.user.profile?.studentId ?? 'N/A',
        department: r.user.profile?.department ?? 'N/A',
        courseYear: r.user.profile?.courseYear ?? 'N/A',
        registrationStatus: r.status,
        attemptStatus: attempt?.status ?? null,
        attemptScore: attempt?.totalScore ?? null,
      };
    });
  }

  // ==========================================
  // Start Batch
  // ==========================================

  async startBatch(
    mockDriveId: string,
    batchId: string,
    instituteId: string
  ): Promise<BatchDetails> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
      include: { _count: { select: { registrations: true } } },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    if (batch.status !== MockDriveBatchStatus.CREATED && 
        batch.status !== MockDriveBatchStatus.SCHEDULED) {
      throw new BatchStatusError(batch.status, 'start');
    }

    if (batch._count.registrations === 0) {
      throw new BatchError('NO_STUDENTS', 'Cannot start batch with no students', 400);
    }

    await prisma.mockDriveBatch.update({
      where: { id: batchId },
      data: { status: MockDriveBatchStatus.IN_PROGRESS, actualStartTime: new Date() },
    });

    logger.info('Batch started', { batchId });
    return this.getBatchDetails(batchId);
  }

  // ==========================================
  // Complete Batch
  // ==========================================

  async completeBatch(
    mockDriveId: string,
    batchId: string,
    instituteId: string
  ): Promise<BatchDetails> {
    await this.verifyAccess(mockDriveId, instituteId);

    const batch = await prisma.mockDriveBatch.findUnique({
      where: { id: batchId },
    });

    if (!batch || batch.mockDriveId !== mockDriveId) {
      throw new BatchNotFoundError(batchId);
    }

    if (batch.status !== MockDriveBatchStatus.IN_PROGRESS) {
      throw new BatchStatusError(batch.status, 'complete');
    }

    await prisma.$transaction([
      prisma.mockDriveBatch.update({
        where: { id: batchId },
        data: { status: MockDriveBatchStatus.COMPLETED, actualEndTime: new Date() },
      }),
      prisma.mockDriveAttempt.updateMany({
        where: { batchId, status: MockDriveAttemptStatus.IN_PROGRESS },
        data: { status: MockDriveAttemptStatus.TIMED_OUT, completedAt: new Date() },
      }),
    ]);

    logger.info('Batch completed', { batchId });
    return this.getBatchDetails(batchId);
  }

  // ==========================================
  // Private Helpers
  // ==========================================

  private async verifyAccess(mockDriveId: string, instituteId: string): Promise<MockDriveInfo> {
    const mockDrive = await prisma.mockDrive.findUnique({
      where: { id: mockDriveId },
      select: {
        id: true,
        status: true,
        instituteId: true,
        driveStartDate: true,
        driveEndDate: true,
        modules: { where: { isActive: true }, select: { timeLimit: true } },
      },
    });

    if (!mockDrive) throw new MockDriveNotFoundError(mockDriveId);
    if (mockDrive.instituteId !== instituteId) throw new MockDriveAccessDeniedError();

    return {
      ...mockDrive,
      totalModuleTime: mockDrive.modules.reduce((sum, m) => sum + m.timeLimit, 0),
    };
  }

  private validateStatusForBatchOps(status: MockDriveStatus): void {
  const valid: MockDriveStatus[] = [
  MockDriveStatus.PUBLISHED,
  MockDriveStatus.REGISTRATION_OPEN,
  MockDriveStatus.REGISTRATION_CLOSED,
  MockDriveStatus.IN_PROGRESS,
];
    if (!valid.includes(status)) {
      throw new MockDriveInvalidStatusError(status, 'manage batches');
    }
  }

  private validateTimeWithinDrive(mockDrive: MockDriveInfo, start: Date, end: Date): void {
    if (mockDrive.driveStartDate && start < mockDrive.driveStartDate) {
      throw new BatchScheduleConflictError('Start time is before drive start date');
    }
    if (mockDrive.driveEndDate && end > mockDrive.driveEndDate) {
      throw new BatchScheduleConflictError('End time is after drive end date');
    }
  }

  private validateStatusTransition(current: MockDriveBatchStatus, next: MockDriveBatchStatus): void {
    const transitions: Record<MockDriveBatchStatus, MockDriveBatchStatus[]> = {
      [MockDriveBatchStatus.CREATED]: [MockDriveBatchStatus.SCHEDULED, MockDriveBatchStatus.IN_PROGRESS, MockDriveBatchStatus.CANCELLED],
      [MockDriveBatchStatus.SCHEDULED]: [MockDriveBatchStatus.IN_PROGRESS, MockDriveBatchStatus.CANCELLED],
      [MockDriveBatchStatus.IN_PROGRESS]: [MockDriveBatchStatus.COMPLETED, MockDriveBatchStatus.CANCELLED],
      [MockDriveBatchStatus.COMPLETED]: [],
      [MockDriveBatchStatus.CANCELLED]: [],
    };

    if (!transitions[current].includes(next)) {
      throw new BatchStatusError(current, `transition to ${next}`);
    }
  }

  private validateActiveUpdateFields(data: UpdateBatchDTO, status: MockDriveBatchStatus): void {
    const allowed = ['notes', 'status'];
    const attempted = Object.keys(data).filter((k) => data[k as keyof UpdateBatchDTO] !== undefined);
    const restricted = attempted.filter((f) => !allowed.includes(f));

    if (restricted.length > 0) {
      throw new BatchStatusError(status, `update: ${restricted.join(', ')}`);
    }
  }

  private async checkScheduleConflict(
    mockDriveId: string,
    start: Date,
    end: Date,
    excludeId?: string
  ): Promise<void> {
    const conflict = await prisma.mockDriveBatch.findFirst({
      where: {
        mockDriveId,
        ...(excludeId && { id: { not: excludeId } }),
        status: { not: MockDriveBatchStatus.CANCELLED },
        OR: [
          { scheduledStartTime: { lte: start }, scheduledEndTime: { gt: start } },
          { scheduledStartTime: { lt: end }, scheduledEndTime: { gte: end } },
          { scheduledStartTime: { gte: start }, scheduledEndTime: { lte: end } },
        ],
      },
    });

    if (conflict) {
      throw new BatchScheduleConflictError(`Conflicts with: ${conflict.name}`);
    }
  }

  private async getNextBatchNumber(mockDriveId: string): Promise<number> {
    const last = await prisma.mockDriveBatch.findFirst({
      where: { mockDriveId },
      orderBy: { batchNumber: 'desc' },
      select: { batchNumber: true },
    });
    return (last?.batchNumber ?? 0) + 1;
  }

  private buildUpdateData(data: UpdateBatchDTO): Prisma.MockDriveBatchUpdateInput {
    const update: Prisma.MockDriveBatchUpdateInput = {};

    if (data.name !== undefined) update.name = data.name;
    if (data.scheduledStartTime !== undefined) update.scheduledStartTime = data.scheduledStartTime;
    if (data.scheduledEndTime !== undefined) update.scheduledEndTime = data.scheduledEndTime;
    if (data.maxCapacity !== undefined) update.maxCapacity = data.maxCapacity;
    if (data.notes !== undefined) update.notes = data.notes;

    if (data.status !== undefined) {
      update.status = data.status;
      if (data.status === MockDriveBatchStatus.IN_PROGRESS) update.actualStartTime = new Date();
      if (data.status === MockDriveBatchStatus.COMPLETED) update.actualEndTime = new Date();
    }

    return update;
  }

  private async getBatchDetails(batchId: string): Promise<BatchDetails> {
    const batch = await prisma.mockDriveBatch.findUnique({ where: { id: batchId } });
    if (!batch) throw new BatchNotFoundError(batchId);

    const stats = await this.getBatchStats(batchId);

    return {
      id: batch.id,
      mockDriveId: batch.mockDriveId,
      name: batch.name,
      batchNumber: batch.batchNumber,
      scheduledStartTime: batch.scheduledStartTime,
      scheduledEndTime: batch.scheduledEndTime,
      status: batch.status,
      maxCapacity: batch.maxCapacity,
      isAutoGenerated: batch.isAutoGenerated,
      notes: batch.notes,
      actualStartTime: batch.actualStartTime,
      actualEndTime: batch.actualEndTime,
      createdAt: batch.createdAt,
      updatedAt: batch.updatedAt,
      stats,
    };
  }

  private async getBatchStats(batchId: string): Promise<BatchStats> {
    const [assigned, attempts, avgScore] = await Promise.all([
      prisma.mockDriveRegistration.count({ where: { batchId } }),
      prisma.mockDriveAttempt.groupBy({
        by: ['status'],
        where: { batchId },
        _count: { id: true },
      }),
      prisma.mockDriveAttempt.aggregate({
        where: { batchId, status: MockDriveAttemptStatus.COMPLETED },
        _avg: { totalScore: true },
      }),
    ]);

    const statusMap = new Map(attempts.map((a) => [a.status, a._count.id]));

    return {
      totalAssigned: assigned,
      totalStarted:
        (statusMap.get(MockDriveAttemptStatus.IN_PROGRESS) ?? 0) +
        (statusMap.get(MockDriveAttemptStatus.COMPLETED) ?? 0) +
        (statusMap.get(MockDriveAttemptStatus.TIMED_OUT) ?? 0),
      totalCompleted: statusMap.get(MockDriveAttemptStatus.COMPLETED) ?? 0,
      totalInProgress: statusMap.get(MockDriveAttemptStatus.IN_PROGRESS) ?? 0,
      averageScore: avgScore._avg.totalScore,
    };
  }

  private async getAttemptCountsByBatch(
    batchIds: string[]
  ): Promise<Map<string, { completed: number; inProgress: number }>> {
    const stats = await prisma.mockDriveAttempt.groupBy({
      by: ['batchId', 'status'],
      where: { batchId: { in: batchIds } },
      _count: { id: true },
    });

    const map = new Map<string, { completed: number; inProgress: number }>();

    for (const stat of stats) {
      if (!map.has(stat.batchId)) {
        map.set(stat.batchId, { completed: 0, inProgress: 0 });
      }
      const entry = map.get(stat.batchId)!;
      if (stat.status === MockDriveAttemptStatus.COMPLETED) {
        entry.completed = stat._count.id;
      } else if (stat.status === MockDriveAttemptStatus.IN_PROGRESS) {
        entry.inProgress = stat._count.id;
      }
    }

    return map;
  }
}

export const batchService = new BatchService();