// prisma/seed.ts

import {
  PrismaClient,
  UserRole,
  QuestionType,
  DifficultyLevel,
  TestCaseType,
  MockDriveStatus,
  MockDriveModuleType,
  MockDriveRegistrationStatus,
  MockDriveBatchStatus,
  MockDriveAttemptStatus,
  MockDriveModuleAttemptStatus,
  Prisma,
} from '@prisma/client';
import bcrypt from 'bcryptjs';
import { promises as fs } from 'fs';
import path from 'path';

// Create a dedicated Prisma client for seeding
const prisma = new PrismaClient({
  log: ['error', 'warn'],
});

// =====================================================
// TYPE DEFINITIONS
// =====================================================

// Type definitions for aptitude questions JSON
interface AptitudeOptionData {
  id: string;
  text: string;
}

interface AptitudeQuestionData {
  questionText: string;
  questionType: 'QUANTITATIVE' | 'VERBAL' | 'LOGICAL';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  explanation?: string;
  correctOptionId: string;
  options: AptitudeOptionData[];
}

// Type definitions for machine questions JSON
interface TestCaseData {
  input: string;
  expectedOutput: string;
  type: 'SAMPLE' | 'HIDDEN';
  order?: number;
}

interface MachineQuestionData {
  title: string;
  description: string;
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  inputFormat: string;
  outputFormat: string;
  constraints: string[];
  tags: string[];
  testCases: TestCaseData[];
}

// Type definitions for programming languages JSON
interface ProgrammingLanguageData {
  name: string;
  monacoId: string;
  judge0Id: number;
  template: string;
  isActive?: boolean;
}

// Type definitions for mock drive JSON
interface MockDriveData {
  id: string;
  instituteId: string;
  title: string;
  description?: string;
  instructions?: string;
  status: string;
  registrationStartDate?: string;
  registrationEndDate?: string;
  maxRegistrations?: number;
  driveStartDate?: string;
  driveEndDate?: string;
  allowLateSubmission: boolean;
  showLeaderboard: boolean;
  showResultsImmediately: boolean;
  resultsReleaseDate?: string;
  shuffleQuestions: boolean;
  enableProctoring: boolean;
  proctoringSettings?: unknown;
  questionsGenerated: boolean;
  questionsGeneratedAt?: string;
}

interface EligibilityData {
  id: string;
  mockDriveId: string;
  minCgpa?: number;
  maxCgpa?: number;
  minMarks10?: number;
  minMarks12?: number;
  allowedDepartmentIds: string[];
  allowedCourseYears: string[];
  requiredSkills: string[];
  maxBacklogs?: number;
  customRules?: unknown;
}

// Module config types
interface AptitudeModuleConfig {
  difficulty: DifficultyLevel;
  questionTypes: QuestionType[];
  numberOfQuestions: number;
  marksPerQuestion: number;
  negativeMarking: number;
}

interface MachineCodingModuleConfig {
  difficulty: DifficultyLevel;
  numberOfQuestions: number;
  allowedLanguages: string[];
  partialScoring: boolean;
  maxScorePerQuestion: number;
}

interface AiInterviewModuleConfig {
  difficulty: string;
  jobTitle: string;
  companyName?: string;
  focusAreas: string[];
  targetQuestions: number;
}

type ModuleConfig = AptitudeModuleConfig | MachineCodingModuleConfig | AiInterviewModuleConfig;

interface ModuleData {
  id: string;
  mockDriveId: string;
  moduleType: string;
  order: number;
  name?: string;
  timeLimit: number;
  weightage: number;
  config: ModuleConfig;
  passingScore?: number;
  instructions?: string;
  isActive: boolean;
}

interface BatchData {
  id: string;
  mockDriveId: string;
  name: string;
  batchNumber: number;
  scheduledStartTime: string;
  scheduledEndTime: string;
  status: string;
  maxCapacity?: number;
  isAutoGenerated: boolean;
  notes?: string;
  actualStartTime?: string;
  actualEndTime?: string;
}

interface RegistrationData {
  id: string;
  mockDriveId: string;
  userEmail: string;
  status: string;
  eligibilityCheckResult?: unknown;
  adminNotes?: string;
  batchId?: string;
  registeredAt: string;
  reviewedAt?: string;
  reviewedBy?: string;
}

interface AttemptData {
  id: string;
  mockDriveId: string;
  batchId: string;
  userEmail: string;
  status: string;
  currentModuleOrder: number;
  startedAt?: string;
  completedAt?: string;
  totalScore?: number;
  percentageScore?: number;
  rank?: number;
  isPassed?: boolean;
  moduleScoresSummary?: unknown;
  browserInfo?: string;
  ipAddress?: string;
  deviceInfo?: unknown;
  tabSwitchCount: number;
  suspiciousActivity?: unknown;
}

interface ModuleAttemptData {
  id: string;
  attemptId: string;
  moduleId: string;
  status: string;
  startedAt?: string;
  completedAt?: string;
  expiresAt?: string;
  timeSpentSeconds: number;
  score?: number;
  maxScore?: number;
  percentage?: number;
  isPassed?: boolean;
  moduleData?: unknown;
  isAutoSubmitted: boolean;
}

interface ReportData {
  id: string;
  attemptId: string;
  overallScore: number;
  overallPercentage: number;
  overallRank?: number;
  totalParticipants?: number;
  performanceSummary: string;
  strengths: string[];
  weaknesses: string[];
  moduleFeedback: unknown;
  percentile?: number;
  comparedToAverage?: number;
  recommendations: string[];
  aiInsights?: string;
}

interface LeaderboardData {
  id: string;
  mockDriveId: string;
  batchId?: string;
  userEmail: string;
  studentName: string;
  studentId?: string;
  departmentId?: string;
  totalScore: number;
  percentageScore: number;
  rank: number;
  moduleScores: unknown;
  totalTimeTaken?: number;
  completedAt?: string;
}

interface MockDriveJsonData {
  mockDrives: MockDriveData[];
  eligibilityCriteria: EligibilityData[];
  modules: ModuleData[];
  batches: BatchData[];
  registrations: RegistrationData[];
  attempts: AttemptData[];
  moduleAttempts: ModuleAttemptData[];
  reports: ReportData[];
  leaderboard: LeaderboardData[];
}

// =====================================================
// HELPER FUNCTIONS
// =====================================================

// Helper function to safely convert to Prisma JSON (for nullable fields)
function toJsonValue(value: unknown): Prisma.InputJsonValue | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }
  return value as Prisma.InputJsonValue;
}

// Helper function for required JSON fields (non-nullable)
function toJsonValueRequired(value: unknown): Prisma.InputJsonValue {
  if (value === undefined || value === null) {
    return {};
  }
  return value as Prisma.InputJsonValue;
}

// Seeded shuffle for reproducible randomization
function seededShuffle<T>(array: T[], seed: string): T[] {
  const result = [...array];
  let seedNum = seed.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  
  for (let i = result.length - 1; i > 0; i--) {
    seedNum = (seedNum * 9301 + 49297) % 233280;
    const j = Math.floor((seedNum / 233280) * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  
  return result;
}

// =====================================================
// MAIN SEED FUNCTION
// =====================================================

async function seed() {
  try {
    console.log('🌱 Starting database seeding...\n');

    // ==================== INSTITUTES ====================
    console.log('📁 Seeding institutes...');
    const institutesData = JSON.parse(
      await fs.readFile(
        path.join(process.cwd(), 'prisma/data/institutes.json'),
        'utf-8'
      )
    );

    for (const institute of institutesData) {
      await prisma.institute.upsert({
        where: { domain: institute.domain },
        update: {
          name: institute.name,
          isActive: institute.isActive ?? true,
        },
        create: {
          id: institute.id,
          domain: institute.domain,
          name: institute.name,
          isActive: institute.isActive ?? true,
        },
      });
    }
    console.log(`   ✅ Seeded ${institutesData.length} institutes`);

    // ==================== USERS ====================
    console.log('👥 Seeding users...');
    const usersData = JSON.parse(
      await fs.readFile(
        path.join(process.cwd(), 'prisma/data/users.json'),
        'utf-8'
      )
    );

    for (const userData of usersData) {
      const hashedPassword = await bcrypt.hash(userData.password, 12);

      let instituteId: string | null = null;
      if (userData.instituteDomain) {
        const institute = await prisma.institute.findUnique({
          where: { domain: userData.instituteDomain },
        });
        instituteId = institute?.id ?? null;
      }

      await prisma.user.upsert({
        where: { email: userData.email },
        update: {
          password: hashedPassword,
          name: userData.name,
          role: userData.role as UserRole,
          instituteId,
          isActive: userData.isActive ?? true,
        },
        create: {
          email: userData.email,
          password: hashedPassword,
          name: userData.name,
          role: userData.role as UserRole,
          instituteId,
          isActive: userData.isActive ?? true,
        },
      });
    }
    console.log(`   ✅ Seeded ${usersData.length} users`);

    // ==================== APTITUDE QUESTIONS ====================
    console.log('📝 Seeding aptitude questions...');
    const aptitudeQuestionsData: AptitudeQuestionData[] = JSON.parse(
      await fs.readFile(
        path.join(process.cwd(), 'prisma/data/aptitude-questions.json'),
        'utf-8'
      )
    );

    // Clear existing aptitude data for clean re-seeding
    await prisma.aptitudeOption.deleteMany({});
    await prisma.aptitudeQuestion.deleteMany({});

    for (const questionData of aptitudeQuestionsData) {
      // First create options to get their IDs
      const optionIds: Record<string, string> = {};

      const question = await prisma.aptitudeQuestion.create({
        data: {
          questionText: questionData.questionText,
          questionType: questionData.questionType as QuestionType,
          difficulty: questionData.difficulty as DifficultyLevel,
          explanation: questionData.explanation,
          correctOptionId: '', // Temporary, will update after creating options
          isActive: true,
        },
      });

      // Create options
      for (const optionData of questionData.options) {
        const option = await prisma.aptitudeOption.create({
          data: {
            text: optionData.text,
            questionId: question.id,
          },
        });
        optionIds[optionData.id] = option.id;
      }

      // Update question with correct option ID
      await prisma.aptitudeQuestion.update({
        where: { id: question.id },
        data: {
          correctOptionId: optionIds[questionData.correctOptionId],
        },
      });
    }
    console.log(`   ✅ Seeded ${aptitudeQuestionsData.length} aptitude questions`);

    // ==================== MACHINE QUESTIONS ====================
    console.log('💻 Seeding machine questions...');
    const machineQuestionsData: MachineQuestionData[] = JSON.parse(
      await fs.readFile(
        path.join(process.cwd(), 'prisma/data/machine-tests.json'),
        'utf-8'
      )
    );

    // Clear existing machine data for clean re-seeding
    await prisma.testCase.deleteMany({});
    await prisma.machineQuestion.deleteMany({});

    let totalTestCases = 0;

    for (const questionData of machineQuestionsData) {
      const machineQuestion = await prisma.machineQuestion.create({
        data: {
          title: questionData.title,
          description: questionData.description,
          difficulty: questionData.difficulty as DifficultyLevel,
          inputFormat: questionData.inputFormat,
          outputFormat: questionData.outputFormat,
          constraints: questionData.constraints,
          tags: questionData.tags,
          isActive: true,
        },
      });

      // Create test cases for this question
      for (let i = 0; i < questionData.testCases.length; i++) {
        const testCaseData = questionData.testCases[i];
        await prisma.testCase.create({
          data: {
            input: testCaseData.input,
            expectedOutput: testCaseData.expectedOutput,
            type: testCaseData.type as TestCaseType,
            order: testCaseData.order ?? i,
            questionId: machineQuestion.id,
          },
        });
        totalTestCases++;
      }
    }
    console.log(
      `   ✅ Seeded ${machineQuestionsData.length} machine questions with ${totalTestCases} test cases`
    );

    // ==================== PROGRAMMING LANGUAGES ====================
    console.log('🔧 Seeding programming languages...');
    const programmingLanguagesData: ProgrammingLanguageData[] = JSON.parse(
      await fs.readFile(
        path.join(process.cwd(), 'prisma/data/programming-languages.json'),
        'utf-8'
      )
    );

    for (const langData of programmingLanguagesData) {
      await prisma.programmingLanguage.upsert({
        where: { judge0Id: langData.judge0Id },
        update: {
          name: langData.name,
          monacoId: langData.monacoId,
          template: langData.template,
          isActive: langData.isActive ?? true,
        },
        create: {
          name: langData.name,
          monacoId: langData.monacoId,
          judge0Id: langData.judge0Id,
          template: langData.template,
          isActive: langData.isActive ?? true,
        },
      });
    }
    console.log(
      `   ✅ Seeded ${programmingLanguagesData.length} programming languages`
    );

    // ==================== MOCK DRIVES ====================
    console.log('\n🎯 Seeding mock drive data...');
    
    const mockDriveJsonData: MockDriveJsonData = JSON.parse(
      await fs.readFile(
        path.join(process.cwd(), 'prisma/data/mock-drive.json'),
        'utf-8'
      )
    );

    // Clear existing mock drive data for clean re-seeding (in correct order due to foreign keys)
    console.log('   🗑️  Clearing existing mock drive data...');
    await prisma.mockDriveLeaderboard.deleteMany({});
    await prisma.mockDriveReport.deleteMany({});
    await prisma.mockDriveModuleAttempt.deleteMany({});
    await prisma.mockDriveAttempt.deleteMany({});
    await prisma.mockDriveRegistration.deleteMany({});
    await prisma.mockDriveBatch.deleteMany({});
    await prisma.mockDriveModuleQuestion.deleteMany({});
    await prisma.mockDriveModule.deleteMany({});
    await prisma.mockDriveEligibility.deleteMany({});
    await prisma.mockDrive.deleteMany({});

    // Create a map of user emails to user IDs
    const userEmailToId: Record<string, string> = {};
    const allUsers = await prisma.user.findMany({
      select: { id: true, email: true },
    });
    for (const user of allUsers) {
      userEmailToId[user.email] = user.id;
    }

    // Seed Mock Drives
    for (const driveData of mockDriveJsonData.mockDrives) {
      await prisma.mockDrive.create({
        data: {
          id: driveData.id,
          instituteId: driveData.instituteId,
          title: driveData.title,
          description: driveData.description,
          instructions: driveData.instructions,
          status: driveData.status as MockDriveStatus,
          registrationStartDate: driveData.registrationStartDate
            ? new Date(driveData.registrationStartDate)
            : null,
          registrationEndDate: driveData.registrationEndDate
            ? new Date(driveData.registrationEndDate)
            : null,
          maxRegistrations: driveData.maxRegistrations,
          driveStartDate: driveData.driveStartDate
            ? new Date(driveData.driveStartDate)
            : null,
          driveEndDate: driveData.driveEndDate
            ? new Date(driveData.driveEndDate)
            : null,
          allowLateSubmission: driveData.allowLateSubmission,
          showLeaderboard: driveData.showLeaderboard,
          showResultsImmediately: driveData.showResultsImmediately,
          resultsReleaseDate: driveData.resultsReleaseDate
            ? new Date(driveData.resultsReleaseDate)
            : null,
          shuffleQuestions: driveData.shuffleQuestions,
          enableProctoring: driveData.enableProctoring,
          proctoringSettings: toJsonValue(driveData.proctoringSettings),
          questionsGenerated: driveData.questionsGenerated,
          questionsGeneratedAt: driveData.questionsGeneratedAt
            ? new Date(driveData.questionsGeneratedAt)
            : null,
        },
      });
    }
    console.log(`   ✅ Seeded ${mockDriveJsonData.mockDrives.length} mock drives`);

    // Seed Eligibility Criteria
    for (const eligData of mockDriveJsonData.eligibilityCriteria) {
      await prisma.mockDriveEligibility.create({
        data: {
          id: eligData.id,
          mockDriveId: eligData.mockDriveId,
          minCgpa: eligData.minCgpa,
          maxCgpa: eligData.maxCgpa,
          minMarks10: eligData.minMarks10,
          minMarks12: eligData.minMarks12,
          allowedDepartmentIds: eligData.allowedDepartmentIds,
          allowedCourseYears: eligData.allowedCourseYears,
          requiredSkills: eligData.requiredSkills,
          maxBacklogs: eligData.maxBacklogs,
          customRules: toJsonValue(eligData.customRules),
        },
      });
    }
    console.log(
      `   ✅ Seeded ${mockDriveJsonData.eligibilityCriteria.length} eligibility criteria`
    );

    // Seed Modules
    for (const moduleData of mockDriveJsonData.modules) {
      await prisma.mockDriveModule.create({
        data: {
          id: moduleData.id,
          mockDriveId: moduleData.mockDriveId,
          moduleType: moduleData.moduleType as MockDriveModuleType,
          order: moduleData.order,
          name: moduleData.name,
          timeLimit: moduleData.timeLimit,
          weightage: moduleData.weightage,
          config: toJsonValueRequired(moduleData.config),
          passingScore: moduleData.passingScore,
          instructions: moduleData.instructions,
          isActive: moduleData.isActive,
        },
      });
    }
    console.log(`   ✅ Seeded ${mockDriveJsonData.modules.length} modules`);

    // ==================== GENERATE MODULE QUESTIONS ====================
    // For drives that have questionsGenerated = true, we need to populate MockDriveModuleQuestion
    console.log('   🔄 Generating module questions...');
    
    // Fetch all aptitude questions from DB
    const allAptitudeQuestions = await prisma.aptitudeQuestion.findMany({
      where: { isActive: true },
      select: { id: true, difficulty: true, questionType: true },
    });

    // Fetch all machine questions from DB
    const allMachineQuestions = await prisma.machineQuestion.findMany({
      where: { isActive: true },
      select: { id: true, difficulty: true },
    });

    let totalModuleQuestionsSeeded = 0;

    for (const driveData of mockDriveJsonData.mockDrives) {
      if (!driveData.questionsGenerated) continue;

      const driveModules = mockDriveJsonData.modules.filter(
        (m) => m.mockDriveId === driveData.id
      );

      for (const moduleData of driveModules) {
        const config = moduleData.config;

        if (moduleData.moduleType === 'APTITUDE') {
          const aptitudeConfig = config as AptitudeModuleConfig;
          
          // Filter questions by difficulty and types
          let eligibleQuestions = allAptitudeQuestions.filter(
            (q) =>
              q.difficulty === aptitudeConfig.difficulty &&
              aptitudeConfig.questionTypes.includes(q.questionType)
          );

          // Use seeded shuffle for reproducible results
          const shuffled = seededShuffle(eligibleQuestions, moduleData.id);
          const selected = shuffled.slice(0, aptitudeConfig.numberOfQuestions);

          // Create module questions
          for (let i = 0; i < selected.length; i++) {
            await prisma.mockDriveModuleQuestion.create({
              data: {
                moduleId: moduleData.id,
                aptitudeQuestionId: selected[i].id,
                order: i,
              },
            });
            totalModuleQuestionsSeeded++;
          }
        } else if (moduleData.moduleType === 'MACHINE_CODING') {
          const machineConfig = config as MachineCodingModuleConfig;
          
          // Filter questions by difficulty
          let eligibleQuestions = allMachineQuestions.filter(
            (q) => q.difficulty === machineConfig.difficulty
          );

          // Use seeded shuffle for reproducible results
          const shuffled = seededShuffle(eligibleQuestions, moduleData.id);
          const selected = shuffled.slice(0, machineConfig.numberOfQuestions);

          // Create module questions
          for (let i = 0; i < selected.length; i++) {
            await prisma.mockDriveModuleQuestion.create({
              data: {
                moduleId: moduleData.id,
                machineQuestionId: selected[i].id,
                order: i,
              },
            });
            totalModuleQuestionsSeeded++;
          }
        }
        // AI_INTERVIEW modules don't have pre-selected questions (generated dynamically)
      }
    }
    console.log(`   ✅ Generated ${totalModuleQuestionsSeeded} module questions`);

    // Seed Batches
    for (const batchData of mockDriveJsonData.batches) {
      await prisma.mockDriveBatch.create({
        data: {
          id: batchData.id,
          mockDriveId: batchData.mockDriveId,
          name: batchData.name,
          batchNumber: batchData.batchNumber,
          scheduledStartTime: new Date(batchData.scheduledStartTime),
          scheduledEndTime: new Date(batchData.scheduledEndTime),
          status: batchData.status as MockDriveBatchStatus,
          maxCapacity: batchData.maxCapacity,
          isAutoGenerated: batchData.isAutoGenerated,
          notes: batchData.notes,
          actualStartTime: batchData.actualStartTime
            ? new Date(batchData.actualStartTime)
            : null,
          actualEndTime: batchData.actualEndTime
            ? new Date(batchData.actualEndTime)
            : null,
        },
      });
    }
    console.log(`   ✅ Seeded ${mockDriveJsonData.batches.length} batches`);

    // Seed Registrations
    let registrationsSeeded = 0;
    let registrationsSkipped = 0;
    for (const regData of mockDriveJsonData.registrations) {
      const userId = userEmailToId[regData.userEmail];
      if (!userId) {
        registrationsSkipped++;
        continue;
      }

      await prisma.mockDriveRegistration.create({
        data: {
          id: regData.id,
          mockDriveId: regData.mockDriveId,
          userId: userId,
          status: regData.status as MockDriveRegistrationStatus,
          eligibilityCheckResult: toJsonValue(regData.eligibilityCheckResult),
          adminNotes: regData.adminNotes,
          batchId: regData.batchId,
          registeredAt: new Date(regData.registeredAt),
          reviewedAt: regData.reviewedAt ? new Date(regData.reviewedAt) : null,
          reviewedBy: regData.reviewedBy,
        },
      });
      registrationsSeeded++;
    }
    if (registrationsSkipped > 0) {
      console.log(`   ⚠️  Skipped ${registrationsSkipped} registrations (users not found)`);
    }
    console.log(`   ✅ Seeded ${registrationsSeeded} registrations`);

    // Seed Attempts
    let attemptsSeeded = 0;
    let attemptsSkipped = 0;
    for (const attemptData of mockDriveJsonData.attempts) {
      const userId = userEmailToId[attemptData.userEmail];
      if (!userId) {
        attemptsSkipped++;
        continue;
      }

      await prisma.mockDriveAttempt.create({
        data: {
          id: attemptData.id,
          mockDriveId: attemptData.mockDriveId,
          batchId: attemptData.batchId,
          userId: userId,
          status: attemptData.status as MockDriveAttemptStatus,
          currentModuleOrder: attemptData.currentModuleOrder,
          startedAt: attemptData.startedAt
            ? new Date(attemptData.startedAt)
            : null,
          completedAt: attemptData.completedAt
            ? new Date(attemptData.completedAt)
            : null,
          totalScore: attemptData.totalScore,
          percentageScore: attemptData.percentageScore,
          rank: attemptData.rank,
          isPassed: attemptData.isPassed,
          moduleScoresSummary: toJsonValue(attemptData.moduleScoresSummary),
          browserInfo: attemptData.browserInfo,
          ipAddress: attemptData.ipAddress,
          deviceInfo: toJsonValue(attemptData.deviceInfo),
          tabSwitchCount: attemptData.tabSwitchCount,
          suspiciousActivity: toJsonValue(attemptData.suspiciousActivity),
        },
      });
      attemptsSeeded++;
    }
    if (attemptsSkipped > 0) {
      console.log(`   ⚠️  Skipped ${attemptsSkipped} attempts (users not found)`);
    }
    console.log(`   ✅ Seeded ${attemptsSeeded} attempts`);

    // Seed Module Attempts
    for (const modAttemptData of mockDriveJsonData.moduleAttempts) {
      await prisma.mockDriveModuleAttempt.create({
        data: {
          id: modAttemptData.id,
          attemptId: modAttemptData.attemptId,
          moduleId: modAttemptData.moduleId,
          status: modAttemptData.status as MockDriveModuleAttemptStatus,
          startedAt: modAttemptData.startedAt
            ? new Date(modAttemptData.startedAt)
            : null,
          completedAt: modAttemptData.completedAt
            ? new Date(modAttemptData.completedAt)
            : null,
          expiresAt: modAttemptData.expiresAt
            ? new Date(modAttemptData.expiresAt)
            : null,
          timeSpentSeconds: modAttemptData.timeSpentSeconds,
          score: modAttemptData.score,
          maxScore: modAttemptData.maxScore,
          percentage: modAttemptData.percentage,
          isPassed: modAttemptData.isPassed,
          moduleData: toJsonValue(modAttemptData.moduleData),
          isAutoSubmitted: modAttemptData.isAutoSubmitted,
        },
      });
    }
    console.log(
      `   ✅ Seeded ${mockDriveJsonData.moduleAttempts.length} module attempts`
    );

    // Seed Reports
    for (const reportData of mockDriveJsonData.reports) {
      await prisma.mockDriveReport.create({
        data: {
          id: reportData.id,
          attemptId: reportData.attemptId,
          overallScore: reportData.overallScore,
          overallPercentage: reportData.overallPercentage,
          overallRank: reportData.overallRank,
          totalParticipants: reportData.totalParticipants,
          performanceSummary: reportData.performanceSummary,
          strengths: reportData.strengths,
          weaknesses: reportData.weaknesses,
          moduleFeedback: toJsonValueRequired(reportData.moduleFeedback),
          percentile: reportData.percentile,
          comparedToAverage: reportData.comparedToAverage,
          recommendations: reportData.recommendations,
          aiInsights: reportData.aiInsights,
        },
      });
    }
    console.log(`   ✅ Seeded ${mockDriveJsonData.reports.length} reports`);

    // Seed Leaderboard
    let leaderboardSeeded = 0;
    let leaderboardSkipped = 0;
    for (const lbData of mockDriveJsonData.leaderboard) {
      const userId = userEmailToId[lbData.userEmail];
      if (!userId) {
        leaderboardSkipped++;
        continue;
      }

      await prisma.mockDriveLeaderboard.create({
        data: {
          id: lbData.id,
          mockDriveId: lbData.mockDriveId,
          batchId: lbData.batchId,
          userId: userId,
          studentName: lbData.studentName,
          studentId: lbData.studentId,
          departmentId: lbData.departmentId,
          totalScore: lbData.totalScore,
          percentageScore: lbData.percentageScore,
          rank: lbData.rank,
          moduleScores: toJsonValueRequired(lbData.moduleScores),
          totalTimeTaken: lbData.totalTimeTaken,
          completedAt: lbData.completedAt ? new Date(lbData.completedAt) : null,
        },
      });
      leaderboardSeeded++;
    }
    if (leaderboardSkipped > 0) {
      console.log(`   ⚠️  Skipped ${leaderboardSkipped} leaderboard entries (users not found)`);
    }
    console.log(`   ✅ Seeded ${leaderboardSeeded} leaderboard entries`);

    // ==================== SUMMARY ====================
    console.log('\n' + '═'.repeat(60));
    console.log('✅ DATABASE SEEDED SUCCESSFULLY');
    console.log('═'.repeat(60));
    console.log('');
    console.log('📊 CORE DATA:');
    console.log('─'.repeat(40));
    console.log(`   📁 Institutes:              ${institutesData.length}`);
    console.log(`   👥 Users:                   ${usersData.length}`);
    console.log(`   📝 Aptitude Questions:      ${aptitudeQuestionsData.length}`);
    console.log(`   💻 Machine Questions:       ${machineQuestionsData.length}`);
    console.log(`   🧪 Test Cases:              ${totalTestCases}`);
    console.log(`   🔧 Programming Languages:   ${programmingLanguagesData.length}`);
    console.log('');
    console.log('🎯 MOCK DRIVE DATA:');
    console.log('─'.repeat(40));
    console.log(`   🎯 Mock Drives:             ${mockDriveJsonData.mockDrives.length}`);
    console.log(`   📋 Eligibility Criteria:    ${mockDriveJsonData.eligibilityCriteria.length}`);
    console.log(`   📦 Modules:                 ${mockDriveJsonData.modules.length}`);
    console.log(`   ❓ Module Questions:        ${totalModuleQuestionsSeeded}`);
    console.log(`   📅 Batches:                 ${mockDriveJsonData.batches.length}`);
    console.log(`   📝 Registrations:           ${registrationsSeeded}`);
    console.log(`   🎮 Attempts:                ${attemptsSeeded}`);
    console.log(`   📊 Module Attempts:         ${mockDriveJsonData.moduleAttempts.length}`);
    console.log(`   📄 Reports:                 ${mockDriveJsonData.reports.length}`);
    console.log(`   🏆 Leaderboard Entries:     ${leaderboardSeeded}`);
    console.log('═'.repeat(60));
    console.log('');
  } catch (error) {
    console.error('\n❌ Error seeding database:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run the seed function
seed()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });