services:
  - type: web
    name: preplyte-api
    env: node
    rootDir: backend
    region: singapore
    plan: free
    
    buildCommand: pnpm install --frozen-lockfile && pnpm prisma:generate && pnpm build
    startCommand: pnpm start:prod
    releaseCommand: pnpm prisma:migrate:prod
    
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

